/* fstPedNoise.idl
*
* Table: fstPedNoise
*
* description: FST detector channel pedestal, rms noise and common mode noise
*
*/
struct fstPedNoise {
    unsigned short cmNoise[288][9];         /* 100 * cm noise in ADC counts per chip      */
    unsigned short pedestal[36864][9];     /* pedestal in ADC counts per channel   */
    unsigned short totNoise[36864][9];     /* 100 * total noise in ADC counts per channel  */
    unsigned short ranNoise[36864][9];     /* 100 * random noise in ADC counts per channel  */
};
